### ISSUE TITLE
发现一个友邻项目：https://github.com/aben1188/awesome-uni-app

### ISSUE THREAD

**Issue by xiayulu** [uni-helper/awesome-uni-app#4]
### 对问题的清晰和简明的描述

略

### 推荐的解决方案

略

### 替代方案

略

### 额外上下文

略

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by KeJunMao** [comment]
那个已经很久不维护了，如果你有兴趣可以提pr在这里
